lugares = ['eua', 'canada', 'brasil', 'inglaterra', 'alemanha', 'japão']
print("1 - " + str(lugares))
print("2 - " + str(sorted(lugares)))
print("3 - " + str(lugares))
print("4 - " + str(sorted(lugares, reverse=True)))
print("5 - " + str(lugares))
lugares.reverse()
print("6 - " + str(lugares))
lugares.reverse()
print("7 - " + str(lugares))
lugares.sort()
print("8 - " + str(lugares))
lugares.sort(reverse=True)
print("9 - " + str(lugares))